Add onclick functions to Option buttons
googleinterns/step47-2020 pull request #18
Opened 2020-07-09 16:14 UTC by emilyzhaoo

Add onclick functions to option buttons to allow automatic search when clicked by user.

2020-07-09 19:52 UTC, nabil-dbz approved these changes

2020-07-09 19:52 UTC, nabil-dbz commented on planet/src/main/webapp/places.js
> +    let input = document.getElementById('pac-input');
nit: this can be a const since its value is not changing

2020-07-09 19:52 UTC, nabil-dbz commented on planet/src/main/webapp/places.js
>      document.getElementById('greeting').innerHTML = "Find a place: " + document.getElementById('pac-input').value;
nit: single quotes for "Find a place: "

2020-07-10 14:58 UTC, EkkiD requested changes

2020-07-10 14:58 UTC, EkkiD commented on planet/src/main/webapp/places.js
> +    google.maps.event.trigger(input, 'keydown', { keyCode: 13 });
what key is this? I'm guessing Enter?

Add a comment saying what these 3 lines are doing and why they're necessary

2020-07-10 17:49 UTC, EkkiD approved these changes
LGTM

2020-07-10 18:08 UTC, merged