Display Saved Icons on Refresh
googleinterns/step47-2020 pull request #56
Opened 2020-07-31 15:46 UTC by emilyzhaoo

Display previously saved places as "Saved" after refresh of page.

2020-07-31 18:45 UTC, azhang72 approved these changes

2020-07-31 21:31 UTC, EkkiD requested changes

2020-07-31 21:31 UTC, EkkiD commented on planet/src/main/webapp/places.js
> +        // Check if place is already saved in database
This comment is just repeating the code. It doesn't help the user understand.

Instead, we can explain _why_ the fact that it's in the database affects the styling.

E.g.
// Places are in the database if and only if they've been favourited by the user.

2020-08-04 15:56 UTC, EkkiD approved these changes
LGTM

2020-08-04 18:28 UTC, merged